---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: podinfo
  namespace: xonery-namespace
spec:
  releaseName: podinfo
  serviceAccountName: xonery-serviceaccount
  chart:
    spec:
      chart: podinfo
      version: ">=1.0.0"
      sourceRef:
        name: podinfo
        kind: HelmRepository
        namespace: xonery-ns
  interval: 30m
  install:
    remediation:
      retries: 3
  values:
    tls:
      enabled: false
    ingress:
      enabled: false
