---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: xonery-tls
  namespace: xonery-namespace
spec:
  secretName: xonery-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: xonery.dev
  dnsNames:
    - xonery.dev
    # Subdomains
    - podinfo.xonery.dev
